[templates.dmsspicetify]
input_path = 'SHELL_DIR/matugen/templates/spicetify-color.ini'
output_path = 'CONFIG_DIR/spicetify/Themes/Dreary/color.ini'
post_hook = '/nix/store/z3advc83bpcj8r9glhd1mpcrwzddycxy-spicetify-cli-2.42.8/share/spicetify/spicetify apply'
